"""Create tables

Revision ID: 440fd87c7b67
Revises: 
Create Date: 2024-01-23 19:16:27.864179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440fd87c7b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('useremail', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('isInstructor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userAttendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('attendanceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendanceId'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userSubjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userSubjects')
    op.drop_table('userAttendances')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('contents')
    op.drop_table('attendances')
    # ### end Alembic commands ###
